export const matrixScenes = [
  {
    code: "M02",
    family: "Lattice",
    title: "Cortes da malha 512×512×nD",
    statement:
      "The live document opens on the stack itself: one active 512×512 plane, one tile zoom, one persistent reading frame.",
    centerLabel: "active plane 512×512",
    detailLabel: "tile 8×8 zoom",
    mapLabel: "Dk → tile → cell trail",
    centerType: "stack",
    palette: { center: "#7aa8ff", detail: "#ffc857", plane: "#53e0b7", map: "#ff6d6d" },
    planes: [
      { name: "D4", note: "previous reference plane" },
      { name: "D3", note: "active comparison band" },
      { name: "D2", note: "next fixed anchor" },
    ],
    nodes: ["D4", "D3", "D2", "tile", "cell"],
    excerpt: `nD stack (cada camada = 512×512)\n\n Dk  ┌──────────────────────────┐\n     │       plano 512×512      │\n     └──────────────────────────┘\n ...\nTile 8×8 (zoom)\n\ny7  • • • • • • • •\ny0  • • • • • • • •`,
  },
  {
    code: "M08",
    family: "Runtime",
    title: "Runtime Base 4-Stack",
    statement:
      "The center turns into a layered contract stack. The scene stops talking only about geometry and starts exposing runtime order.",
    centerLabel: "semantic / skin / engine / contracts",
    detailLabel: "active handoff layer",
    mapLabel: "stack descent",
    centerType: "tower",
    palette: { center: "#8bb5ff", detail: "#f6bd60", plane: "#4fd8b0", map: "#f86b8a" },
    planes: [
      { name: "semantic", note: "top interpretive layer" },
      { name: "engine", note: "execution middle" },
      { name: "contracts", note: "hard floor" },
    ],
    nodes: ["semantic", "skin", "engine", "contracts"],
    excerpt: `SEMANTIC\n   ↓\nSKIN\n   ↓\nENGINE\n   ↓\nCONTRACTS`,
  },
  {
    code: "M19",
    family: "AGM",
    title: "AGM matriz 8×8 de portais 128D",
    statement:
      "The center becomes a portal field. The detail isolates a single portal and the planes stabilize the semantic neighborhood around it.",
    centerLabel: "8×8 portal field",
    detailLabel: "single portal focus",
    mapLabel: "portal activation path",
    centerType: "portal",
    palette: { center: "#7fd2ff", detail: "#ffd166", plane: "#55dba6", map: "#ff7c5c" },
    planes: [
      { name: "P2x", note: "upper portal band" },
      { name: "P4x", note: "active semantic row" },
      { name: "P6x", note: "lower portal band" },
    ],
    nodes: ["P12", "P24", "P43", "P56", "P77"],
    excerpt: `AGM\n8 × 8 portais semânticos 128D\n\n┌────┬────┬────┬────┐\n│ P00│ P01│ P02│ P03│\n├────┼────┼────┼────┤\n│ P40│ P41│ P42│ P43│\n└────┴────┴────┴────┘`,
  },
  {
    code: "M20",
    family: "AGM",
    title: "AGM zoom do portal / SPL SN3 8×8×8",
    statement:
      "The center compresses into one portal cube. The detail tracks ring and phase while the planes keep the cube legible through the cut.",
    centerLabel: "portal cube 8×8×8",
    detailLabel: "ring / phase nibble",
    mapLabel: "portal → SN3 route",
    centerType: "cube-grid",
    palette: { center: "#78a6ff", detail: "#ffcf70", plane: "#4be0c2", map: "#ff6e91" },
    planes: [
      { name: "z6", note: "upper slice" },
      { name: "z3", note: "active slice" },
      { name: "z0", note: "base slice" },
    ],
    nodes: ["portal", "ring", "phase", "fold", "resolve"],
    excerpt: `portal 128D\n   │\n   ▼\nSPL / SN3 8×8×8\n\nz7 ┌─────────────────┐\nz0 └─────────────────┘`,
  },
  {
    code: "M23",
    family: "Governance",
    title: "GV.REC triângulo GV",
    statement:
      "The map stops being neutral. It carries structural tension between anti-loop, recursion, and promotion pressure.",
    centerLabel: "decision triangle",
    detailLabel: "promotion witness",
    mapLabel: "GV.REC tension loop",
    centerType: "triangle",
    palette: { center: "#9aa8ff", detail: "#ffb86b", plane: "#5ae1ba", map: "#ff6b7a" },
    planes: [
      { name: "anti-loop", note: "budget restraint" },
      { name: "recursor", note: "inherit / compat" },
      { name: "promotion", note: "proof pressure" },
    ],
    nodes: ["budget", "anti-loop", "recursor", "promotion"],
    excerpt: `GV.REC.01\nLOOM / budget / anti-loop\n      /\\\n     /  \\\n    /____\\\nRECURSOR  PROMOCAO`,
  },
  {
    code: "M35",
    family: "LOOM",
    title: "LOOM barramento 7 eixos × 512 × n16 × ±",
    statement:
      "The scene shifts from planes to pressure lines. Seven axes pulse around the center as a bus, while detail zooms into one micro-port.",
    centerLabel: "7-axis loom bus",
    detailLabel: "axis / port / nibble / sign",
    mapLabel: "bus pressure trace",
    centerType: "bus",
    palette: { center: "#7ca8ff", detail: "#ffd166", plane: "#42d6aa", map: "#ff7a59" },
    planes: [
      { name: "A-C", note: "upper axis bundle" },
      { name: "D", note: "active axis spine" },
      { name: "E-G", note: "lower axis bundle" },
    ],
    nodes: ["A+", "C+", "D-", "F+", "G-"],
    excerpt: `LOOM.BUS\n\nA B C D E F G\n┌────────┐\n│ 0..511 │\n│ n0..15 │\n│  + / - │\n└────────┘`,
  },
];
