#!/usr/bin/env python3
"""Generate a starter ACG config from repository structure."""

from __future__ import annotations

import argparse
from pathlib import Path

COMMON_DIRS = [
    "src",
    "app",
    "api",
    "web",
    "frontend",
    "backend",
    "infra",
    "scripts",
    "tests",
    "docs",
    "examples",
    ".github",
]

ROOT_FILES = [
    "README.md",
    "SPEC.md",
    "QUICKSTART.md",
    "USER_GUIDE.md",
    "KNOWN_LIMITATIONS.md",
    "PUBLISHING_GUIDE.md",
    "CHANGELOG.md",
    "THREAT_MODEL.md",
    "LICENSE.md",
    "VERSION",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="ACG bootstrap config generator")
    parser.add_argument("--repo", default=".")
    parser.add_argument("--output", default="")
    parser.add_argument("--force", action="store_true")
    return parser.parse_args()


def detect_project_name(repo_root: Path) -> str:
    return repo_root.name or "acg-project"


def detect_allowed(repo_root: Path) -> list[str]:
    allowed: list[str] = []
    for name in ROOT_FILES:
        if (repo_root / name).exists():
            allowed.append(name)

    for name in COMMON_DIRS:
        if (repo_root / name).exists():
            allowed.append(f"{name}/**")

    if (repo_root / "schemas").exists():
        allowed.append("schemas/**")

    if (repo_root / "acg.yaml").exists():
        allowed.append("acg.yaml")

    return allowed or ["README.md", "src/**", "tests/**", ".github/**"]


def detect_verify_commands(repo_root: Path) -> list[str]:
    commands: list[str] = []
    if (repo_root / "tests").exists():
        commands.append("python3 -m unittest discover -s tests -p 'test_*.py'")

    js_candidates = [
        repo_root / "examples" / "acg-structure-scout" / "script.js",
        repo_root / "src" / "index.js",
        repo_root / "src" / "index.ts",
    ]
    for candidate in js_candidates:
        if candidate.exists():
            commands.append(f"node --check {candidate.relative_to(repo_root).as_posix()}")
            break

    if not commands:
        commands.append("python3 -c \"print('configure verify.commands')\"")
    return commands


def render_config(repo_root: Path) -> str:
    project_name = detect_project_name(repo_root)
    allowed = detect_allowed(repo_root)
    verify_commands = detect_verify_commands(repo_root)

    lines = [
        "project:",
        f"  name: {project_name}",
        "  default_branch: main",
        "",
        "task:",
        f"  id: {project_name}-bootstrap",
        '  description: "Starter config generated by acg-bootstrap"',
        "  scope:",
        "    allowed:",
    ]
    for item in allowed:
        lines.append(f"      - {item}")

    lines.extend(
        [
            "    forbidden:",
            "      - .env",
            "      - .env.*",
            "      - secrets/**",
            "      - *.pem",
            "  done_when:",
            '    - file_exists: "README.md"',
            "",
            "verify:",
            "  commands:",
        ]
    )
    for command in verify_commands:
        lines.append(f"    - {command}")

    lines.extend(
        [
            "",
            "promotion:",
            "  fail_closed: true",
            "  require_evidence: true",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    args = parse_args()
    repo_root = Path(args.repo).resolve()
    content = render_config(repo_root)
    if not args.output:
        print(content)
        return 0

    output = Path(args.output)
    if not output.is_absolute():
        output = repo_root / output
    if output.exists() and not args.force:
        raise SystemExit(f"Refusing to overwrite existing file: {output}")
    output.write_text(content, encoding="utf-8")
    print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
